BUILD HTML

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -1,30 +1,35 @@
 #!/bin/bash
 # publish org files.
 
-# check references
-echo ">>>>>>>>>> check references <<<<<<<<<<"
+echo "********** check references **********"
 python ./scripts/check-ref-images.py
 if [ $? != 0 ]; then
     echo "resolve ref issues!"
     exit 1
 fi
 
-# compress images
-echo ">>>>>>>>>> compress images <<<<<<<<<<"
-python ./scripts/compress-images.py
+echo "********** enforce org format **********"
+python $HOME/.private/project/pyscript/utils/enforce-org-format.py `pwd`
+if [ $? != 0 ]; then
+    echo "enforce org format failed"
+    exit 1
+fi
+
+echo "********** compress images **********"
+python $HOME/.private/project/pyscript/utils/compress-images.py `pwd`/images
 if [ $? != 0 ]; then
     echo "compress images failed"
     exit 1
 fi
 
-# echo ">>>>>>>>>> git rebase master <<<<<<<<<<"
+# echo "********** git rebase master **********"
 # git pull origin master
 # if [ $? != 0 ]; then
 #     echo "git add & commit!"
 #     exit 1
 # fi
 
-echo ">>>>>>>>>> emacs publish  <<<<<<<<<<"
+echo "********** emacs publish  **********"
 # find emacs binary.
 kernel=`uname -s`
 emacs="emacs"
@@ -40,10 +45,10 @@ if [ $? != 0 ]; then
 fi
 
 # post processing html files.
-echo ">>>>>>>>>> post publish  <<<<<<<<<<"
+echo "********** post publish  **********"
 python3 ./scripts/pp-html
 
-echo ">>>>>>>>>> git push master  <<<<<<<<<<"
+echo "********** git push master  **********"
 git add .
 git commit -a -m 'BUILD HTML'
 git push origin master
